#!/bin/sh

CONFIG_STOW=$HOME
STOW_FILES=("i3" "tmux" "tmux-sessionizer" "personal" "nvim" "zsh" )
# Delete old config files before stowing
for dir in "${STOW_FILES[@]}"
do
	rm -rf $XDG_CONFIG_HOME/"$dir"
done

rm -f $HOME/.zshrc $HOME/.zsh_profile $HOME/.gitconfig
# Stow config files
stow -d "$DOTFILES" -t "$HOME" \
	pconfig \
	zsh \
	nvim \
	git

INSTALL_SCRIPTS_DIR=$DOTFILES/s_scripts


for i_script in $( find $INSTALL_SCRIPTS_DIR -maxdepth 2 -type f -not -path '*./\.*' )
do 
	# Uncomment in a fresh install
	# ./"$i_script"
	echo "$i_script"
done

