#!/bin/sh

curl -L https://github.com/dundee/gdu/releases/latest/download/gdu_linux_amd64.tgz | tar xz -C ~/Downloads/
chmod +x ~/Downloads/gdu_linux_amd64
sudo mv ~/Downloads/gdu_linux_amd64 /usr/bin/gdu
