#!/bin/sh

sudo dnf install tmux fzf

git clone https://github.com/ThePrimeagen/tmux-sessionizer.git ~/.local/tmux-sessionizer && \
mv ~/.local/tmux-sessionizer/tmux-sessionizer ~/.local/bin/ && \
rm -rf ~/.local/tmux-sessionizer

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
